services:

  emm-db:
    container_name: emm-db
    image: postgres
    restart: always
    hostname: emm_psql_machine
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack

    # networks: host
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/project_emm/:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: emmuser
      POSTGRES_PASSWORD: emmpwd
      POSTGRES_DB: emm
    # We override the default command to enable pg_stat_statements.
    # See https://github.com/docker-library/docs/blob/master/postgres/README.md#database-configuration
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c pg_stat_statements.max=10000000 -c pg_stat_statements.track_planning=true

  emm-cli:
    image: emm-cli:custom
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: emm-cli
    links:
      - emm-db
    depends_on:
      - emm-db
    volumes:
      # We use this volume to attach the code to run
      - .:/home/emm
    environment:
      EMM_CONFIG: docker
    # This allow the container to run the container like with -i and -t.
    # Keeping STDIN open and attaching pseudo-tty
    stdin_open: true
    tty: true

volumes:
  pgdata:
